markdown: kramdown
highlighter: pygments
permalink: posts/:title.html
excerpt_separator: ""

blog:
  name: Jerry's Blog
  description: This is Jerry's Blog
  title: Jerry's Blog
  url: http://xiajie.me
  static: http://7xkon6.com1.z0.glb.clouddn.com/
  #static: /

author:
  name: 夏杰
  nickname: Jerry
  sign: To strive to become a habit
  email: jerry@xiajie.me
  weibo: http://weibo.com/Jerry9916
  qq: 82269916
  weixin: clever_jerry
  github: https://github.com/jerryhsia
  resume: http://resume.xiajie.me

douban:
  name: 88880966
  key:  0fe4cdb47009b0a72fae691d501d11f5

duoshuo: 
  enable: true
  name: jerry9916

lang:
  email: 邮箱联系我
  timing: 时间轴
  category: 目录
  books: 书架
  about: 关于
  weibo: 新浪微博
  github: Github
  to_top: 返回顶部
  read_all: 阅读全文
  prev_post: 上一篇
  next_post: 下一篇
  prev_page: 上一页
  next_page: 下一页
  page_not_found: 页面找不到了
  redrect_tip: 秒后跳转到首页
