markdown: kramdown
highlighter: pygments
permalink: posts/:title.html
paginate: 4
paginate_path: page/:num
excerpt_separator: ""

blog:
    name: Jerry's Blog # 博客名称
    sign: To strive to become a habit # 博客签名
    description: This is Jerry's Blog # 博客描述
    title: Jerry's Blog # 网页标题
    url: http://xiajie.me # 博客地址

author:
    name: 夏杰 # 作者名称
    nickname: Jerry Hsia
    email: xiajie9916@gmail.com # 邮箱地址
    weibo: http://weibo.com/Jerry9916 # 微博地址
    github: https://github.com/JerryHsia # GitHub地址
    avatar: /assets/images/avatar.jpg # logo地址

douban:
    name: 88880966 # 豆瓣账号ID
    key:  0fe4cdb47009b0a72fae691d501d11f5  # 豆瓣API Key
