markdown: kramdown
highlighter: pygments
permalink: posts/:title.html
paginate: 4
paginate_path: pages/:num.html
excerpt_separator: ""

blog:
  name: Jerry's Blog
  sign: To strive to become a habit
  description: This is Jerry's blog
  title: Jerry's blog
  url: http://xiajie.me

author:
  name: 夏杰
  nickname: Jerry Hsia
  email: xiajie9916@gmail.com
  weibo: http://weibo.com/Jerry9916
  github: https://github.com/jerryhsia
  resume: http://resume.xiajie.me

douban:
  name: 88880966
  key:  0fe4cdb47009b0a72fae691d501d11f5

duoshuo: 
  enable: true
  name: jerry9916

static:
  files: http://7xj4ee.com1.z0.glb.clouddn.com/files
  images: /assets/images
  styles: /assets/styles
  scripts: /assets/scripts



lang:
  email: 邮箱联系我
  timing: 时间轴
  category: 分类
  read: 阅读
  about: 关于
  weibo: 新浪微博
  github: Github
  to_top: 返回顶部
  read_all: 阅读全文
  prev_post: 上一篇
  next_post: 下一篇
  prev_page: 上一页
  next_page: 下一页
